#!/bin/bash

cython hello.pyx

# Compile the object file
#gcc -c -fPIC -I/usr/local/include/python2.6/ hello.c

# Link it into a shared library
#gcc -shared hello.o -o hello.so

#Make sure to use 64-bit gcc or it will complain about LONG size or some shit
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I /usr/include/python2.6 -o hello.so hello.c
